import { useEffect, useMemo, useRef, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

const DEFAULT_API = "https://bitey-system-bots-trading-api.onrender.com";
type Tick = { timestamp?: string | number; bid?: number; ask?: number; last?: number; spread?: number; error?: string };
type Candle = { time?: string | number; timestamp?: string | number; open: number; high: number; low: number; close: number; volume?: number };
type Market = { id: string; label: string; examples: string[] };
type Analysis = { [key: string]: any };
const MARKETS: Market[] = [
  { id: "forex", label: "Divisas", examples: ["EURUSD", "GBPUSD", "USDJPY", "USDBRL"] },
  { id: "indices", label: "Índices", examples: ["US30", "NAS100", "SPX500", "GER40"] },
  { id: "stocks", label: "Acciones", examples: ["AAPL", "MSFT", "NVDA", "TSLA"] },
  { id: "crypto", label: "Crypto", examples: ["BTCUSD", "ETHUSD", "SOLUSD"] },
  { id: "commodities", label: "Materias primas", examples: ["XAUUSD", "XAGUSD", "USOIL"] },
];
const TIMEFRAMES = ["M1", "M5", "M15", "M30", "H1", "H4", "D1"];
const COPY = { es: { title: "Bitey SBT", subtitle: "Trading intelligence y mercado en tiempo real", market: "Mercado", timeframe: "Temporalidad", connected: "CONECTADO", disconnected: "SIN CONEXIÓN", price: "Precio", bid: "Bid", ask: "Ask", spread: "Spread", gateway: "Bitey SBT Market Gateway", analyze: "ANALIZAR MERCADO", event: "Evento", result: "Market Intelligence", candles: "Velas OHLC", loadingCandles: "Cargando velas…", noCandles: "Sin velas disponibles para este instrumento", note: "SBT es la plataforma de trading. MT5, Alpaca, TradingView y otros proveedores son conectores; las credenciales no pasan por la app." } } as const;
function wsUrl(api: string, symbol: string) { const base = api.replace(/\/$/, "").replace(/^http:/, "ws:").replace(/^https:/, "wss:"); return `${base}/api/v1/market/stream/${encodeURIComponent(symbol)}`; }
function candlesUrl(api: string, symbol: string, timeframe: string) { return `${api.replace(/\/$/, "")}/api/v1/market/candles/${encodeURIComponent(symbol)}?timeframe=${encodeURIComponent(timeframe)}&limit=80`; }
function pct(v: any) { return typeof v === "number" ? `${Math.round(v * 100)}%` : "—"; }
function titleCase(v: any) { return String(v ?? "—").replaceAll("_", " ").replace(/\b\w/g, (x) => x.toUpperCase()); }
function Card({ title, status, children }: { title: string; status?: string; children: React.ReactNode }) { return <View style={styles.card}><View style={styles.rowBetween}><Text style={styles.section}>{title}</Text>{status && <Text style={styles.badge}>{status}</Text>}</View>{children}</View>; }
function Metric({ label, value, explanation }: { label: string; value: string; explanation: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text><Text style={styles.explain}>{explanation}</Text></View>; }
function Detail({ label, value, text }: { label: string; value: string; text: string }) { return <View style={styles.detail}><View style={styles.rowBetween}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View><Text style={styles.explain}>{text}</Text></View>; }

export default function Home() {
  const [apiUrl, setApiUrl] = useState(DEFAULT_API), [market, setMarket] = useState("forex"), [symbol, setSymbol] = useState("EURUSD"), [timeframe, setTimeframe] = useState("M5");
  const [event, setEvent] = useState("market_structure"), [loading, setLoading] = useState(false), [loadingCandles, setLoadingCandles] = useState(false), [analysis, setAnalysis] = useState<Analysis | null>(null), [tick, setTick] = useState<Tick | null>(null), [candles, setCandles] = useState<Candle[]>([]), [connected, setConnected] = useState(false);
  const socketRef = useRef<WebSocket | null>(null); const t = COPY.es; const selectedMarket = MARKETS.find((item) => item.id === market) ?? MARKETS[0];
  useEffect(() => { setTick(null); setConnected(false); const socket = new WebSocket(wsUrl(apiUrl, symbol)); socketRef.current = socket; socket.onopen = () => setConnected(true); socket.onmessage = (m) => { try { const data = JSON.parse(m.data) as Tick; setTick(data); setConnected(!data.error); } catch { setConnected(false); } }; socket.onerror = () => setConnected(false); socket.onclose = () => setConnected(false); return () => { socket.close(); if (socketRef.current === socket) socketRef.current = null; }; }, [apiUrl, symbol]);
  useEffect(() => { let cancelled = false; async function load() { setLoadingCandles(true); try { const r = await fetch(candlesUrl(apiUrl, symbol, timeframe)); if (!r.ok) throw new Error(`HTTP ${r.status}`); const p = await r.json(); const next = Array.isArray(p?.candles) ? p.candles : []; if (!cancelled) setCandles(next.filter((c: Candle) => [c.open, c.high, c.low, c.close].every((v) => Number.isFinite(Number(v)))).slice(-80)); } catch { if (!cancelled) setCandles([]); } finally { if (!cancelled) setLoadingCandles(false); } } load(); return () => { cancelled = true; }; }, [apiUrl, symbol, timeframe]);
  const chart = useMemo(() => { if (!candles.length) return { candles: [], min: 0, max: 0, range: 1 }; const min = Math.min(...candles.map(c => Number(c.low))), max = Math.max(...candles.map(c => Number(c.high))); return { candles, min, max, range: Math.max(max - min, Math.abs(max) * 0.000001, 0.000001) }; }, [candles]);
  async function analyze() { setLoading(true); setAnalysis(null); try { const r = await fetch(`${apiUrl.replace(/\/$/, "")}/api/v1/sbt/market-intelligence/analyze`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ symbol, timeframe, candles, capital: 1000, language: "es", event, evidence: [{ source: "sbt-live-market", source_type: "market", title: `${symbol} ${timeframe} live quote`, reliability: connected ? 1 : 0, impact: 0.5, direction: "neutral" }] }) }); if (!r.ok) throw new Error(`HTTP ${r.status}`); setAnalysis(await r.json()); } catch (e) { setAnalysis({ error: String(e) }); } finally { setLoading(false); } }
  const tech = analysis?.technical, smc = analysis?.smc, pulse = analysis?.market_pulse, cd = analysis?.contradiction_detector, time = analysis?.time_engine, domino = analysis?.domino_state, hypo = analysis?.hypothesis;
  return <ScrollView contentContainerStyle={styles.container}>
    <View style={styles.header}><Text style={styles.eyebrow}>BITEY IA · SBT</Text><Text style={styles.title}>{t.title}</Text><Text style={styles.subtitle}>{t.subtitle}</Text></View>
    <Card title={t.market}><View style={styles.chips}>{MARKETS.map(i => <Pressable key={i.id} onPress={() => { setMarket(i.id); setSymbol(i.examples[0]); }} style={[styles.chip, market === i.id && styles.active]}><Text style={styles.chipText}>{i.label}</Text></Pressable>)}</View><View style={styles.chips}>{selectedMarket.examples.map(i => <Pressable key={i} onPress={() => setSymbol(i)} style={[styles.instrument, symbol === i && styles.active]}><Text style={styles.instrumentText}>{i}</Text></Pressable>)}</View><TextInput value={symbol} onChangeText={setSymbol} autoCapitalize="characters" style={styles.input} /></Card>
    <Card title={`${symbol} · ${timeframe}`} status={connected ? `● ${t.connected}` : `● ${t.disconnected}`}><View style={styles.quoteRow}><Text style={styles.quote}>{t.price}: {tick?.last ?? tick?.bid ?? "—"}</Text><Text style={styles.quote}>{t.bid}: {tick?.bid ?? "—"}</Text><Text style={styles.quote}>{t.ask}: {tick?.ask ?? "—"}</Text><Text style={styles.quote}>{t.spread}: {tick?.spread ?? "—"}</Text></View><Text style={styles.chartTitle}>{t.candles}</Text><View style={styles.chart}>{loadingCandles ? <ActivityIndicator /> : chart.candles.length ? chart.candles.map((c, i) => { const o=+c.open,h=+c.high,l=+c.low,cl=+c.close,top=((chart.max-h)/chart.range)*100,bottom=((chart.max-l)/chart.range)*100,bodyTop=((chart.max-Math.max(o,cl))/chart.range)*100,bodyHeight=Math.max(Math.abs(o-cl)/chart.range*100,1.2),up=cl>=o; return <View key={`${i}-${c.time ?? c.timestamp ?? i}`} style={styles.candleSlot}><View style={[styles.wick,{top:`${top}%`,height:`${Math.max(bottom-top,1)}%`}]} /><View style={[styles.body,up?styles.up:styles.down,{top:`${bodyTop}%`,height:`${bodyHeight}%`}]} /></View>; }) : <Text style={styles.empty}>{t.noCandles}</Text>}</View><View style={styles.chips}>{TIMEFRAMES.map(i => <Pressable key={i} onPress={() => setTimeframe(i)} style={[styles.instrument,timeframe===i&&styles.active]}><Text style={styles.instrumentText}>{i}</Text></Pressable>)}</View><Text style={styles.hint}>{t.gateway} → OHLC {timeframe} → quote WebSocket.</Text></Card>
    <Card title="Market Intelligence" status="RESEARCH ONLY"><Text style={styles.lead}>Antes de operar, entender. SBT separa datos, señales, contradicciones, contexto temporal y consecuencias antes de permitir cualquier experimento.</Text><View style={styles.metricGrid}><Metric label="Sesgo técnico" value={titleCase(pulse?.trend ?? analysis?.bias)} explanation="EMA 9/21 compara tendencia rápida contra la base lenta."/><Metric label="Momentum" value={titleCase(pulse?.momentum)} explanation="RSI 14 identifica presión compradora/vendedora y zonas extremas."/><Metric label="Volatilidad" value={titleCase(pulse?.volatility)} explanation="ATR 14 y rango reciente describen el entorno de riesgo."/><Metric label="Confianza" value={pct(analysis?.confidence)} explanation="Confianza de investigación; no es probabilidad de beneficio."/></View>{pulse?.summary && <View style={styles.summary}><Text style={styles.summaryText}>{pulse.summary}</Text></View>}</Card>
    {analysis && !analysis.error && <>
      <Card title="Market Pulse · EMA structure" status={tech?.ema?.bias ?? "ANALYZE"}><Detail label="EMA rápida" value={tech?.ema?.fast != null ? String(tech.ema.fast) : "—"} text="Periodo 9. Reacciona más rápido a cambios recientes y ayuda a detectar aceleración de tendencia."/><Detail label="EMA lenta" value={tech?.ema?.slow != null ? String(tech.ema.slow) : "—"} text="Periodo 21. Actúa como referencia de tendencia más estable."/><Detail label="Lectura" value={titleCase(tech?.ema?.bias)} text={tech?.ema?.explanation ?? "Compara ambas medias para construir el componente de tendencia."}/></Card>
      <Card title="Market Pulse · RSI momentum" status={tech?.rsi?.state ?? "ANALYZE"}><Detail label="RSI 14" value={tech?.rsi?.value != null ? String(tech.rsi.value) : "—"} text="Mide momentum. 70+ se considera sobrecompra y 30- sobreventa en este modelo."/><Detail label="Dirección" value={titleCase(tech?.rsi?.bias)} text="Las bandas internas 45/55 separan momentum bajista, neutral y alcista."/><Detail label="Interpretación" value={titleCase(tech?.rsi?.state)} text={tech?.rsi?.explanation ?? "El RSI no se utiliza por sí solo para autorizar una operación."}/></Card>
      <Card title="Market Pulse · ATR regime" status={tech?.atr?.regime ?? "RISK INPUT"}><Detail label="ATR 14" value={tech?.atr?.value != null ? String(tech.atr.value) : "—"} text="Mide el rango verdadero medio reciente; aquí funciona como entrada de riesgo, no como dirección."/><Detail label="Régimen" value={titleCase(tech?.atr?.regime)} text="Se compara el rango medio de las últimas 14 velas con las 14 anteriores para detectar expansión o contracción."/></Card>
      <Card title="SMC · Smart Money Concepts" status={smc?.status ?? "READY"}><Detail label="BOS" value={titleCase(smc?.bos)} text="Break of Structure: ruptura del swing de referencia detectada por el motor SMC v1."/><Detail label="CHOCH" value={titleCase(smc?.choch)} text="Change of Character: cambio estructural detectado mediante relaciones de máximos y mínimos."/><Detail label="Liquidez" value={titleCase(smc?.liquidity_sweep)} text="Busca barridos de liquidez sobre máximos/mínimos de referencia antes de interpretar la estructura."/><Detail label="FVG / Order Blocks" value={`${smc?.fair_value_gaps ?? 0} / ${smc?.order_blocks ?? 0}`} text="Zonas investigadas de Fair Value Gap y Order Block. SMC v1 es heurístico y permanece en modo investigación."/><Detail label="Acción SMC" value={titleCase(smc?.action)} text={smc?.explanation ?? "SMC no tiene autoridad para ejecutar órdenes."}/></Card>
      <Card title="Contradiction Detector" status={cd?.status ?? "WATCH"}><Text style={styles.lead}>No busca confirmar una operación; busca razones para desconfiar de una lectura única.</Text>{(cd?.items ?? []).length ? cd.items.map((x: any, i: number) => <View key={i} style={styles.alert}><Text style={styles.alertTitle}>{titleCase(x.title ?? x.type)} · {titleCase(x.severity)}</Text><Text style={styles.explain}>{x.message}</Text><Text style={styles.explain}>{x.effect}</Text></View>) : <Text style={styles.explain}>No se detectaron contradicciones entre las fuentes disponibles en este análisis.</Text>}<Text style={styles.hint}>{cd?.explanation}</Text></Card>
      <Card title="Time Engine" status={time?.status ?? "READY"}><Detail label="Temporalidad" value={time?.timeframe ?? timeframe} text="Determina la escala en la que debe interpretarse la estructura."/><Detail label="Horizonte" value={titleCase(time?.market_horizon)} text={time?.explanation ?? "El horizonte contextual cambia según la temporalidad."}/><Detail label="Contexto de estrategia" value={titleCase(time?.strategy_context)} text={`Ventana típica: ${time?.typical_horizon ?? "—"}. No sustituye un calendario económico ni confirma una sesión concreta.`}/></Card>
      <Card title="Domino State" status={domino?.status ?? "READY"}><Text style={styles.lead}>El estado dominó muestra cómo una hipótesis podría avanzar sin saltarse controles.</Text><View style={styles.flow}>{(domino?.chain ?? ["market_data","technical_context","hypothesis","experiment","validation","risk_gate"]).map((x: string, i: number) => <View key={x} style={styles.flowItem}><Text style={styles.flowIndex}>{i+1}</Text><Text style={styles.flowText}>{titleCase(x)}</Text></View>)}</View><Text style={styles.explain}>{domino?.current_effect ?? "No hay impacto de órdenes autorizado desde Market Intelligence."}</Text></Card>
      <Card title="Hipótesis de mercado" status={hypo?.action ?? "WATCH"}><Detail label="Sesgo" value={titleCase(hypo?.bias)} text={hypo?.thesis ?? "La hipótesis se construye combinando evidencia técnica y estructural."}/><Detail label="Confianza" value={pct(hypo?.confidence)} text="La confianza disminuye cuando aparecen contradicciones; nunca equivale a una garantía de resultado."/><Detail label="Siguiente paso" value={titleCase(hypo?.action)} text="EXPERIMENT significa estudiar/validar la hipótesis. WATCH significa observar hasta resolver incertidumbres."/><View style={styles.blocked}><Text style={styles.blockedTitle}>ORDEN: BLOQUEADA</Text><Text style={styles.explain}>Market Intelligence no puede crear ni enviar una orden. La decisión debe pasar por experimento, backtest/validación y Risk Gate.</Text></View></Card>
    </>}
    <Card title={t.event}><TextInput value={event} onChangeText={setEvent} style={styles.input}/><Pressable onPress={analyze} disabled={loading} style={styles.primary}><Text style={styles.primaryText}>{loading ? "ANALIZANDO…" : t.analyze}</Text></Pressable></Card>
    <Card title={t.gateway}><TextInput value={apiUrl} onChangeText={setApiUrl} autoCapitalize="none" style={styles.input}/><Text style={styles.hint}>{t.note}</Text></Card>
    {loading && <ActivityIndicator size="large"/>}{analysis?.error && <View style={styles.result}><Text style={styles.resultTitle}>Error</Text><Text style={styles.json}>{analysis.error}</Text></View>}
  </ScrollView>;
}
const styles = StyleSheet.create({ container:{padding:20,paddingTop:56,gap:14},header:{gap:5},eyebrow:{fontSize:11,fontWeight:"800",letterSpacing:2,opacity:.6},title:{fontSize:34,fontWeight:"900"},subtitle:{fontSize:16,lineHeight:22,opacity:.65},card:{padding:18,borderRadius:20,borderWidth:1,borderColor:"#ddd",gap:12},section:{fontSize:18,fontWeight:"900"},rowBetween:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",gap:10},badge:{fontSize:10,fontWeight:"900",opacity:.6},chips:{flexDirection:"row",gap:7,flexWrap:"wrap"},chip:{borderWidth:1,borderRadius:14,paddingVertical:10,paddingHorizontal:12},active:{borderWidth:2},chipText:{fontSize:12,fontWeight:"800"},instrument:{borderWidth:1,borderRadius:10,paddingVertical:8,paddingHorizontal:11},instrumentText:{fontSize:11,fontWeight:"800"},input:{borderWidth:1,borderColor:"#ccc",borderRadius:12,padding:13,fontSize:15},quoteRow:{flexDirection:"row",justifyContent:"space-between",gap:6,flexWrap:"wrap"},quote:{fontSize:11,fontWeight:"700"},chartTitle:{fontSize:12,fontWeight:"800",opacity:.65},chart:{height:260,borderRadius:14,borderWidth:1,borderColor:"#ddd",paddingHorizontal:8,paddingVertical:10,flexDirection:"row",gap:2,overflow:"hidden",position:"relative"},candleSlot:{flex:1,position:"relative",minWidth:3},wick:{position:"absolute",width:1,left:"50%",backgroundColor:"#333"},body:{position:"absolute",width:"70%",left:"15%",minHeight:2,borderRadius:1},up:{backgroundColor:"#111"},down:{backgroundColor:"#777"},empty:{margin:"auto",opacity:.5,fontSize:12},hint:{fontSize:11,lineHeight:16,opacity:.58},lead:{fontSize:13,lineHeight:19,opacity:.75},metricGrid:{gap:8},metric:{borderWidth:1,borderColor:"#e3e3e3",borderRadius:14,padding:13,gap:4},metricLabel:{fontSize:11,fontWeight:"800",opacity:.6},metricValue:{fontSize:20,fontWeight:"900"},metricValueSmall:{fontSize:14,fontWeight:"800"},explain:{fontSize:12,lineHeight:17,opacity:.68},summary:{padding:14,borderRadius:14,borderWidth:1,borderColor:"#ddd"},summaryText:{fontSize:13,lineHeight:19,fontWeight:"700"},detail:{gap:4,paddingBottom:10,borderBottomWidth:1,borderBottomColor:"#eee"},detailLabel:{fontSize:12,fontWeight:"800",opacity:.65},detailValue:{fontSize:14,fontWeight:"900"},alert:{padding:13,borderRadius:13,borderWidth:1,borderColor:"#ddd",gap:5},alertTitle:{fontSize:13,fontWeight:"900"},flow:{gap:6},flowItem:{flexDirection:"row",alignItems:"center",gap:10},flowIndex:{width:24,height:24,textAlign:"center",paddingTop:4,borderRadius:12,borderWidth:1,fontWeight:"900"},flowText:{fontSize:13,fontWeight:"800"},blocked:{padding:14,borderRadius:14,borderWidth:1,gap:6},blockedTitle:{fontSize:13,fontWeight:"900"},primary:{padding:16,borderRadius:14,alignItems:"center",backgroundColor:"#111"},primaryText:{color:"#fff",fontWeight:"900"},result:{padding:18,borderRadius:20,borderWidth:1,gap:10},resultTitle:{fontSize:19,fontWeight:"900"},json:{fontFamily:"monospace",fontSize:11,lineHeight:16} });